name: flutter_medloc
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  razorpay_flutter: ^1.1.2
  fluttertoast: ^4.0.1
  firebase_auth: ^0.15.5+3
  table_calendar: ^2.2.3
  url_launcher: ^5.4.2
  flutter_custom_clippers: ^1.1.0
  google_fonts: ^0.5.0+1
  firebase_database: ^3.1.5
  cloud_firestore: ^0.13.7
  smooth_star_rating: 1.1.1
  math_expressions: ^2.0.0
  provider: ^4.3.2+2
  http: ^0.12.2
  app_settings: 4.0.3
  json_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/d1.jpg
    - images/d2.jpg
    - images/d3.jpg
    - images/d4.jpg
    - images/d5.jpg
    - images/d6.jpg
    - images/d8.jpg
    - images/d9.jpg
    - images/d10.jpg
    - images/d11.jpg
    - images/d12.jpg
    - images/d13.jpg
    - images/d15.jpg
    - images/d14.jpg
    - images/d16.jpg
    - images/m1.jpg
    - images/user1.png
    - images/s1.jpg
    - images/s2.jpg
    - images/doc1.jpg
    - images/doc2.jpg
    - images/s3.png
    - images/doc3.png
    - images/doc4.png
    - images/doc5.jpg
    - images/med1.jpg
    - images/med2.jpg
    - images/med3.jpg
    - images/med4.jpg
    - images/med5.jpeg
    - images/med6.jpg
    - images/med7.jpg
    - images/med8.jpg
    - images/as.png
    - images/a3.jpg
    - images/med9.jpeg
    - images/med10.jpg
    - images/med11.jpg
    - images/med12.jpg
    - images/med13.jpg
    - images/med14.jpg
    - images/med15.jpg
    - images/med16.jpg
    - images/med17.jpg
    - images/med19.jpg
    - images/m8.jpg
    - images/m9.jpg
    - images/m17.png
    - images/m18.jpeg
    - images/m19.jpg
    - images/m20.jpg
    - images/m21.jpg
    - images/m22.webp
    - images/m23.webp
    - images/m24.jpg
    - images/t1.jpg
    - images/t2.jpg
    - images/t3.jpg
    - images/t4.webp
    - images/t5.jpg
    - images/t6.webp
    - images/t7.png
    - images/t8.jpg
    - images/t9.jpg
    - images/t10.jpg
    - images/t11.webp
    - images/t12.jpg
    - images/t13.jpg
    - images/t14.jpg
    - images/t15.jpg


  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
